name: Auto Deploy with Watchtower

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout Code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and Push Multi-Arch Images with Docker Compose
        run: |
          docker buildx create --name multi-arch --platform "linux/arm64,linux/amd64,linux/arm/v8,linux/arm/v7" --driver "docker-container"
          docker buildx use multi-arch
          COMPOSE_DOCKER_CLI_BUILD=1
          DOCKER_BUILDKIT=1
          docker compose build --push
